# run: conda env create --file topic_modeling_env.yml

name: topic_modeling_env
channels:
  - anaconda
  - defaults
dependencies:
  - python >= 3.5
  - anaconda
  - pandas = 1.1.5
  - numpy = 1.17.3
  - nltk = 3.4.5
  - gensim = 3.8.3
  - seaborn = 0.10.1
  - pip
  - pip:
    - bs4 == 0.0.1
    - matplotlib == 3.3.0
    - wordcloud == 1.8.0
    - pyldavis == 3.3.1
    - tqdm == 4.61.2
